In [2]:
import numpy as np

In [3]:
# 1. Write a NumPy program to test whether none of the elements of a given array is zero.
# 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.
def checkZero(arr) :
    if np.all(arr) == True :
        return "Non Zero"
    return "Contain Zero"
        
arr = np.array([1,0,2,3,4])
print(checkZero(arr))

Contain Zero


In [40]:
# 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 
arr1 = np.array([1, 2, 3, 4, 5, 6, -7, 8, -9, 10])
arr2 = np.array([4, 2, 3, 4, 5, -7, -7, 8, 60, 10.1])
print("equal : ",np.equal(arr1, arr2))
print("equal within a tolerance : ",np.allclose(arr1, arr2))

equal :  [False  True  True  True  True False  True  True False False]
equal within a tolerance :  False


In [5]:
# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
arr = np.zeros(10)
print(arr)
arr1 = np.ones(10)
print(arr1)
arr2 = np.ones(10)*5
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
# 5. Write a NumPy program to create an array of the integers from 30 to70.
arr = np.arange(30,71,1)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [36]:
# 6. Write a NumPy program to create a 3x3 identity matrix
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
# 7. Write a NumPy program to generate a random number between 0 and 1 
num = np.random.uniform(0, 1)
print(num)

0.9298182512608403


In [35]:
# 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
arr = np.random.uniform(0 , 1 , 15)
print(arr)

[0.0703291  0.52700621 0.24206495 0.0967345  0.40249986 0.62222383
 0.89333361 0.82771388 0.03077362 0.96960738 0.43617916 0.26830945
 0.53766738 0.29289732 0.89130502]


In [41]:
# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
vectors = np.arange(15,55)
print(vectors[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [43]:
# 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10 
vector = np.random.randint(0, 11, 5)
print(vector)

[0 9 7 8 8]


In [131]:
# 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [46]:
# 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
arr = np.diag([1, 2, 3, 4, 5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [47]:
arr = np.zeros((4, 4))
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [106]:
# 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.savez("assignment.npz",arr1 = arr1,arr2 = arr2)
arr = np.load('assignment.npz')
list(arr['arr1'])
list(arr['arr2'])

[5, 6, 7, 8]

In [129]:
# 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select 
arr = np.random.rand(40)
print(arr)

[0.21876935 0.75249617 0.10687958 0.74460324 0.46978529 0.59825567
 0.14762019 0.18403482 0.64507213 0.04862801 0.24861251 0.54240852
 0.22677334 0.38141153 0.92223279 0.92535687 0.56674992 0.53347088
 0.01486002 0.97789926 0.5730289  0.791757   0.56155736 0.87733524
 0.58419583 0.70884983 0.14853345 0.42845074 0.69389007 0.10461974
 0.43960524 0.16620215 0.50697863 0.81903586 0.09010673 0.80006875
 0.56512635 0.58934771 0.19810066 0.43611826]


In [130]:
# 16. Write a NumPy program to extract all numbers from a given array which are less and greater than aspecified number
arr = np.array([[1, 5, 7],
              [11, 14, 16],
              [52, 49, 19]])

arr = arr[arr > 2]
print(arr[arr < 6])

[5]
